version: '3.4'

services:
  djangodockervscode:
    image: djangodockervscode
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 web/app/wsgi.py runserver 0.0.0.0:8888 --nothreading --noreload"]
    ports:
      - 8888:8888
      - 5678:5678
